name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liwwlE8sHCth3tti"
GITHUB_OWNER = "slepoh"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://nav.yormb.cn/api/auth"
NEXT_PUBLIC_API_URL="https://nav.yormb.cn"

